[package]
name = "orchestrate-reconcile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
orchestrate-contracts = { path = "../contracts" }
orchestrate-core = { path = "../core" }
orchestrate-discovery = { path = "../discovery" }
serde_json.workspace = true

[lints]
workspace = true
